#!/usr/bin/env bash

IFS=$' \t\r\n'

INSCRIPTION_PREFIX="https://ordinals.com/inscription/"

if ! which imgcat > /dev/null; then
  echo "Missing dependency: imgcat"
  echo "Install it by running the following command:"
  echo "curl -L https://iterm2.com/misc/install_shell_integration_and_utilities.sh | bash"
  exit 1
fi

while IFS= read -r -a walletInscriptionsOutput; do
  for line in "${walletInscriptionsOutput[@]}"; do
    if [[ $line == *"$INSCRIPTION_PREFIX"* ]]; then
      inscriptionUrl=$(echo "$line" | awk '{print $2}')
      contentUrl=$(echo -e "$inscriptionUrl" | sed 's/inscription/content/' | tr -d '"')
      curl -s "$contentUrl" | imgcat
      echo "$inscriptionUrl" && printf "\n"
    fi
  done
done